Repository wordpress-mobile/AztecEditor-Android, pull requests merged in 2019-10, with the labels that each got.

#855 Issue/fix 854 cant properly insert text on android 7
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/test/kotlin/org/wordpress/aztec/AztecToolbarTest.kt
Labels: bug

#851 Allow paragraph spans that do not extend AlignmentSpan
  aztec/src/main/kotlin/org/wordpress/aztec/AztecParser.kt
  aztec/src/main/kotlin/org/wordpress/aztec/AztecTagHandler.kt
  aztec/src/main/kotlin/org/wordpress/aztec/formatting/BlockFormatter.kt
  aztec/src/main/kotlin/org/wordpress/aztec/source/CssStyleFormatter.kt
  aztec/src/main/kotlin/org/wordpress/aztec/source/Format.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecHeadingSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecListItemSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecListSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecPreformatSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecQuoteSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/HiddenHtmlBlock.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/HiddenHtmlSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/IAztecAlignmentSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/IAztecParagraphStyle.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/ParagraphSpan.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/spans/GutenbergCommentSpan.kt
  wordpress-shortcodes/src/main/java/org/wordpress/aztec/plugins/shortcodes/spans/CaptionShortcodeSpan.kt
Labels: Gutenberg

#834 Fix/ime iob fix
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/main/kotlin/org/wordpress/aztec/ime/EditorInfoUtils.kt
  aztec/src/main/kotlin/org/wordpress/aztec/plugins/CssUnderlinePlugin.kt
Labels: test

#861 [WP-Android 8828] - Detect ArrayIndexOutOfBoundsException exception
  aztec/src/main/kotlin/org/wordpress/aztec/AztecExceptionHandler.kt
  aztec/src/main/kotlin/org/wordpress/aztec/exceptions/DynamicLayoutGetBlockIndexOutOfBoundsException.kt
Labels: bug
