Repository wordpress-mobile/AztecEditor-Android, pull requests merged in 2022-07, with the labels that each got.

#993 Release 1.6.0
  README.md
Labels: release

#996 Move CI to Buildkite
  .buildkite/commands/connected-tests.sh
  .buildkite/commands/lint.sh
  .buildkite/commands/publish-aztec.sh
  .buildkite/commands/publish-glide-loader.sh
  .buildkite/commands/publish-media-placeholders.sh
  .buildkite/commands/publish-picasso-loader.sh
  .buildkite/commands/publish-wordpress-comments.sh
  .buildkite/commands/publish-wordpress-shortcodes.sh
  .buildkite/commands/unit-test.sh
  .buildkite/pipeline.yml
  .circleci/.firebase.secrets.json.enc
  .circleci/config.yml
  .configure
  .configure-files/firebase.secrets.json.enc
  .gitignore
  build.gradle
Labels: enhancement

#995 Clear references in AztecExceptionHandler.kt
  aztec/src/main/kotlin/org/wordpress/aztec/AztecExceptionHandler.kt
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecDynamicImageSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecHorizontalRuleSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecMediaSpan.kt
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/AztecPlaceholderSpan.kt
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/PlaceholderManager.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/spans/GutenbergInlineCommentSpan.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/spans/WordPressCommentSpan.kt
  wordpress-shortcodes/src/main/java/org/wordpress/aztec/plugins/shortcodes/extensions/CaptionExtensions.kt
Labels: bug
