Repository wordpress-mobile/AztecEditor-Android, pull requests merged in 2023-03, with the labels that each got.

#1028 Placeholder doesn't have correct proportions when drawing the first time
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/PlaceholderManager.kt
Labels: bug

#1031 Implement merging of placeholders
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/main/kotlin/org/wordpress/aztec/formatting/LineBlockFormatter.kt
  aztec/src/test/kotlin/org/wordpress/aztec/ImageBlockTest.kt
  media-placeholders/build.gradle
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/ImageWithCaptionAdapter.kt
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/PlaceholderManager.kt
  media-placeholders/src/test/java/org/wordpress/aztec/placeholders/PlaceholderTest.kt
Labels: new feature

#1033 Implement backspace soft override
  aztec/src/main/kotlin/org/wordpress/aztec/Aztec.kt
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/main/kotlin/org/wordpress/aztec/DeleteOverrideInputConnection.kt
  aztec/src/main/kotlin/org/wordpress/aztec/InputConnectionWrapper.kt
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/PlaceholderBackspaceListener.kt
Labels: new feature

#1034 Feature/implement delete or update
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/PlaceholderManager.kt
  media-placeholders/src/test/java/org/wordpress/aztec/placeholders/PlaceholderTest.kt
Labels: new feature

#1039 Update a8c-ci-toolkit Buildkite plugin to new name and latest version
  .buildkite/pipeline.yml
Labels: Tooling
