Repository wordpress-mobile/AztecEditor-Android, pull requests merged in 2023-09, with the labels that each got.

#1059 [Android 14] Update compileSdkVersion to 34
  build.gradle
Labels: Android 14

#1060 Fix issue when removing media in the middle of a paragraph
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/test/kotlin/org/wordpress/aztec/ImageBlockTest.kt
Labels: bug

#1061 Add text size modifier
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/main/kotlin/org/wordpress/aztec/formatting/BlockFormatter.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecHeadingSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecTaskListSpan.kt
Labels: enhancement
