Repository wordpress-mobile/AztecEditor-Android, pull requests merged in 2024-07, with the labels that each got.

#1082 CI: Add YAML Language Server Schema to Allow IDEs to Recognize YML Files
  .buildkite/pipeline.yml
Labels: Tooling

#1083 [Build] Update Kotlin to 1.9.24
  build.gradle
  settings.gradle
Labels: Tooling, Core

#1084 [Dependency Analysis] Add Android Gradle Plugin
  .buildkite/schedules/dependency-analysis.yml
  build.gradle
  gradle.properties
  settings.gradle
Labels: Tooling, Core

#1085 [Dependency Update] Update `a8c-ci-toolkit` to 3.4.2
  .buildkite/pipeline.yml
  .buildkite/schedules/dependency-analysis.yml
  .buildkite/shared-pipeline-vars
Labels: Tooling

#1086 Fix memory leak in EnhancedMovementMethod
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/main/kotlin/org/wordpress/aztec/EnhancedMovementMethod.kt
Labels: Memory Leak

#1087 Remove redundant context from AztecDynamicImageSpan
  aztec/src/main/kotlin/org/wordpress/aztec/AztecTagHandler.kt
  aztec/src/main/kotlin/org/wordpress/aztec/formatting/LineBlockFormatter.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecAudioSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecDynamicImageSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecHorizontalRuleSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecImageSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecMediaSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecVideoSpan.kt
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/AztecPlaceholderSpan.kt
  media-placeholders/src/main/java/org/wordpress/aztec/placeholders/PlaceholderManager.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/HiddenGutenbergPlugin.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/WordPressCommentsPlugin.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/spans/GutenbergInlineCommentSpan.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/spans/WordPressCommentSpan.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/toolbar/MoreToolbarButton.kt
  wordpress-comments/src/main/java/org/wordpress/aztec/plugins/wpcomments/toolbar/PageToolbarButton.kt
Labels: Memory Leak

#1088 Fix media span and task list memory leaks
  aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecMediaSpan.kt
  aztec/src/main/kotlin/org/wordpress/aztec/spans/AztecTaskListSpan.kt
Labels: Memory Leak
